server:
#  port: 8881
  context-path: /

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://120.25.106.62:3307/czm
    username: root
    password: 123456
    minIdle: 1
    maxActive: 2
    initialSize: 1
    timeBetweenEvictionRunsMillis: 3000
    minEvictableIdleTimeMillis: 300000
#    validationQuery: SELECT 'ZTM' FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
#    thymeleaf 模板的配置文件
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: LEGACYHTML5
    check-template: false

#    redis 配置文件
  redis:
    database: 1
    host: 120.25.106.62
    port: 6379
    password: 123456
    timeout: 0
    pool:
      max-active: 8
      max-idle: 8
      max-wait: 1
      min-idle: 0

##mybaits 自動掃描路徑 ，
mybatis:
  #实体类路径
  type-aliases-package: com.czm.entity
  #指定掃描.xml路徑
  mapper-locations: classpath:mybatis/mapper/*.xml

mapper:
    mappers:
        - com.czm.uitl.MyMapper
    not-empty: false
    identity: MYSQL
## 分頁插件 配置
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql


